import { httpClient } from '@/services/api/httpClient';

export interface OfficialMilestone {
  id: string;
  title: string;
  description?: string;
  category: 'motor' | 'cognitivo' | 'linguagem' | 'social' | 'emocional' | 'sensorial';
  target_month: number;
  min_month?: number;
  max_month?: number;
  source: string;
  order_index: number;
  is_active: boolean;
  mappings?: MilestoneMapping[];
}

export interface MilestoneMapping {
  id: string;
  official_milestone_id: string;
  journey_question_id: string;
  weight: string;
  is_auto_generated: boolean;
  verified_by_curator: boolean;
  verified_at?: string;
  verified_by?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  milestone?: {
    id: string;
    title: string;
    category: string;
    target_month: number;
  };
  journeyQuestion?: {
    id: string;
    domain_name: string;
    domain_question: string;
    week: number;
    meta_min_months: number;
  };
  verifier?: {
    id: string;
    name: string;
  };
}

export interface CurationStats {
  totalMilestones: number;
  totalMappings: number;
  autoGenerated: number;
  verified: number;
  pendingReview: number;
  verificationRate: number;
}

export interface ChartData {
  category: string;
  label: string;
  total: number;
  mapped: number;
  coverage: number;
}

export interface LinkedQuestion {
  mapping_id: string;
  question_id: string;
  domain_name: string;
  domain_question: string;
  week: number;
  is_verified: boolean;
  weight: number;
}

export interface CandidateQuestion {
  id: string;
  domain_name: string;
  domain_question: string;
  week: number;
  meta_min_months: number;
}

export interface MilestoneWithCandidates {
  id: string;
  title: string;
  description?: string;
  category: string;
  target_month: number;
  source: string;
  linked_questions: LinkedQuestion[];
  candidate_questions: CandidateQuestion[];
}

export interface AgeRangeGroup {
  range_id: string;
  range_label: string;
  min_month: number;
  max_month: number;
  milestones: MilestoneWithCandidates[];
  milestones_count: number;
}

export interface CurationViewResponse {
  success: boolean;
  data: AgeRangeGroup[];
  total_milestones: number;
}

class MilestonesService {
  async getCurationStats(): Promise<CurationStats> {
    const response = await httpClient.get<{ success: boolean; data: CurationStats }>(
      '/admin/milestones/stats'
    );
    return response.data!;
  }

  async listMilestones(category?: string): Promise<OfficialMilestone[]> {
    const params = category ? `?category=${category}` : '';
    const response = await httpClient.get<{ success: boolean; data: OfficialMilestone[] }>(
      `/admin/milestones/milestones${params}`
    );
    return response.data || [];
  }

  async listMappings(verified?: boolean): Promise<MilestoneMapping[]> {
    const params = verified !== undefined ? `?verified=${verified}` : '';
    const response = await httpClient.get<{ success: boolean; count: number; data: MilestoneMapping[] }>(
      `/admin/milestones/mappings${params}`
    );
    return response.data || [];
  }

  async verifyMapping(id: string, notes?: string): Promise<MilestoneMapping> {
    const response = await httpClient.post<{ success: boolean; data: MilestoneMapping }>(
      `/admin/milestones/mappings/${id}/verify`,
      { notes }
    );
    return response.data!;
  }

  async deleteMapping(id: string): Promise<void> {
    await httpClient.delete(`/admin/milestones/mappings/${id}`);
  }

  async getMilestonesChart(): Promise<ChartData[]> {
    const response = await httpClient.get<{ success: boolean; data: { chartData: ChartData[] } }>(
      '/admin/milestones/dashboard/milestones-chart'
    );
    return response.data?.chartData || [];
  }

  async seedMilestones(): Promise<{ message: string; count: number }> {
    const response = await httpClient.post<{ success: boolean; message: string; count: number }>(
      '/admin/milestones/setup/seed'
    );
    return { message: response.message || '', count: (response as any).count || 0 };
  }

  async autoLink(toleranceWeeks = 4): Promise<{ totalMappings: number; skippedDuplicates: number }> {
    const response = await httpClient.post<{ 
      success: boolean; 
      totalMappings: number; 
      skippedDuplicates: number 
    }>(
      '/admin/milestones/setup/auto-link',
      { toleranceWeeks }
    );
    return { totalMappings: (response as any).totalMappings || 0, skippedDuplicates: (response as any).skippedDuplicates || 0 };
  }

  async getCurationView(): Promise<CurationViewResponse> {
    const response = await httpClient.get<AgeRangeGroup[]>(
      '/admin/milestones/curation-view'
    );
    const ageRanges = Array.isArray(response.data) ? response.data : [];
    return {
      success: response.success ?? true,
      data: ageRanges,
      total_milestones: ageRanges.reduce((sum, range) => sum + (range.milestones_count || 0), 0)
    };
  }

  async createMapping(milestoneId: string, questionId: string, weight: number = 1.0): Promise<MilestoneMapping> {
    const response = await httpClient.post<{ success: boolean; data: MilestoneMapping }>(
      '/admin/milestones/mappings',
      { official_milestone_id: milestoneId, journey_question_id: questionId, weight }
    );
    return response.data!;
  }
}

export const milestonesService = new MilestonesService();
